on:
  push:
    branches:
      - typescript
name: Build and upload TT build for Linux, Windows and Mac

jobs:
  build:
    name: Build and upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Build project
        run: |
          npm run dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Prerelease ${{ github.sha }}
          draft: false
          # TODO: full release on commits matching some pattern? Or maybe only build for those?
          prerelease: true
      - name: Upload Windows build
        id: upload-windows 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/teslaterm-0.1.0-win-x64.zip
          asset_name: teslaterm-0.1.0-win-x64.zip
          asset_content_type: application/zip
      - name: Upload Linux build
        id: upload-linux 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/teslaterm-0.1.0-linux-x64.zip
          asset_name: teslaterm-0.1.0-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload Mac build
        id: upload-mac 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/teslaterm-0.1.0-mac-x64.zip
          asset_name: teslaterm-0.1.0-mac-x64.zip
          asset_content_type: application/zip
