name: Release for tags
on:
  push:
  pull_request:
  create:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  create-artifacts:
    name: Create artifacts
    runs-on: ubuntu-20.04
    env:
      release: ${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Downgrade packages conflicting with wine???
        run: |
          sudo apt-add-repository -y ppa:ondrej/php
          sudo apt-get install ppa-purge
          sudo ppa-purge -y ppa:ondrej/php
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get -f install wine32
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install --dev
      - name: Prepare
        run: npm run build
      - name: Build Electron
        run: npm run package-electron
      - name: Build Node
        run: npm run package-node
      - name: Upload electron-linux
        uses: actions/upload-artifact@v3
        with:
          path: dist/electron/teslaterm-linux.zip
          name: teslaterm-linux.zip
      - name: Upload electron-win
        uses: actions/upload-artifact@v3
        with:
          path: dist/electron/teslaterm-win.zip
          name: teslaterm-windows.zip
      - name: Upload node-linux
        uses: actions/upload-artifact@v3
        with:
          path: dist/node/ud3-node
          name: ud3-node-linux
      - name: Upload node-win
        uses: actions/upload-artifact@v3
        with:
          path: dist/node/ud3-node.exe
          name: ud3-node-windows.exe
      - name: Create and upload release builds
        uses: softprops/action-gh-release@v1
        if: env.release == 'true'
        with:
          files: |
            dist/electron/teslaterm-linux.zip
            dist/electron/teslaterm-win.zip
            dist/node/ud3-node
            dist/node/ud3-node.exe
